#!/usr/bin/env bash
# Generate scan.sh wrappers for all 39 clawhub-lint analyzers
# Also generates publish-all.sh and README.md
set -euo pipefail

REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

TOOLS=(
  accesslint apishield asyncguard authaudit bundlephobia cachelint cloudguard
  concurrencyguard configsafe containerlint cronlint cryptolint dateguard
  deadcode doccoverage envguard errorlens eventlint featurelint gqllint
  httplint i18ncheck inputshield licenseguard logsentry memguard migratesafe
  perfguard pipelinelint ratelint regexguard retrylint schemalint secretscan
  serdelint sqlguard styleguard testgap typedrift
)

echo "Generating scan.sh wrappers for ${#TOOLS[@]} analyzers..."

for tool in "${TOOLS[@]}"; do
  SKILL_DIR="$REPO_DIR/$tool"
  SCRIPTS_DIR="$SKILL_DIR/scripts"

  if [ ! -d "$SCRIPTS_DIR" ]; then
    echo "SKIP: $tool — no scripts/ directory"
    continue
  fi

  # Determine the main entry-point script
  MAIN_SCRIPT=""
  if [ -f "$SCRIPTS_DIR/${tool}.sh" ]; then
    MAIN_SCRIPT="${tool}.sh"
  elif [ -f "$SCRIPTS_DIR/dispatcher.sh" ]; then
    MAIN_SCRIPT="dispatcher.sh"
  else
    echo "WARN: $tool — no main script found, using first .sh that isn't patterns/analyzer/license"
    for f in "$SCRIPTS_DIR"/*.sh; do
      bn=$(basename "$f")
      case "$bn" in
        patterns.sh|analyzer.sh|license.sh|scanner.sh|auditor.sh) continue ;;
        *) MAIN_SCRIPT="$bn"; break ;;
      esac
    done
  fi

  if [ -z "$MAIN_SCRIPT" ]; then
    echo "ERROR: $tool — could not determine main script"
    continue
  fi

  # Count patterns
  PATTERN_COUNT=$(grep -cE '^\s+['"'"'"].*\|' "$SCRIPTS_DIR/patterns.sh" 2>/dev/null || echo "0")

  # Get description from SKILL.md frontmatter
  DESCRIPTION=$(sed -n 's/^description: //p' "$SKILL_DIR/SKILL.md" 2>/dev/null | head -1)

  # Create scan.sh
  cat > "$SCRIPTS_DIR/scan.sh" << 'SCANEOF'
#!/usr/bin/env bash
# scan.sh — Minimal wrapper that sources patterns and runs the scan
# Generated by generate-skills.sh — do not edit manually
#
# Usage: bash scan.sh [file|directory]
#   Defaults to scanning current directory if no argument given.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

SCANEOF

  # Append tool-specific content (not in heredoc so we can interpolate)
  cat >> "$SCRIPTS_DIR/scan.sh" << EOF
# Source patterns for $tool
source "\$SCRIPT_DIR/patterns.sh"

# Delegate to main entry point
exec bash "\$SCRIPT_DIR/$MAIN_SCRIPT" scan "\${@:-.}"
EOF

  chmod +x "$SCRIPTS_DIR/scan.sh"
  echo "OK: $tool/scripts/scan.sh -> $MAIN_SCRIPT (${PATTERN_COUNT} patterns)"
done

# --- Generate publish-all.sh ---

echo ""
echo "Generating publish-all.sh..."

cat > "$REPO_DIR/publish-all.sh" << 'PUBEOF'
#!/usr/bin/env bash
# publish-all.sh — Publish all 39 clawhub-lint analyzers as ClawHub skills
# Usage: bash publish-all.sh [--dry-run]
set -euo pipefail

REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DRY_RUN=false
[[ "${1:-}" == "--dry-run" ]] && DRY_RUN=true

TOOLS=(
  accesslint apishield asyncguard authaudit bundlephobia cachelint cloudguard
  concurrencyguard configsafe containerlint cronlint cryptolint dateguard
  deadcode doccoverage envguard errorlens eventlint featurelint gqllint
  httplint i18ncheck inputshield licenseguard logsentry memguard migratesafe
  perfguard pipelinelint ratelint regexguard retrylint schemalint secretscan
  serdelint sqlguard styleguard testgap typedrift
)

PASSED=0
FAILED=0
SKIPPED=0

for tool in "${TOOLS[@]}"; do
  SKILL_PATH="$REPO_DIR/$tool"

  if [ ! -f "$SKILL_PATH/SKILL.md" ]; then
    echo "SKIP: $tool — no SKILL.md"
    ((SKIPPED++))
    continue
  fi

  if $DRY_RUN; then
    echo "DRY-RUN: clawhub skill publish $SKILL_PATH"
    ((PASSED++))
    continue
  fi

  echo -n "Publishing $tool... "
  if clawhub skill publish "$SKILL_PATH" 2>&1; then
    echo "OK"
    ((PASSED++))
  else
    echo "FAILED"
    ((FAILED++))
  fi
done

echo ""
echo "========================================="
echo "  Published: $PASSED"
echo "  Failed:    $FAILED"
echo "  Skipped:   $SKIPPED"
echo "  Total:     ${#TOOLS[@]}"
echo "========================================="

if [ "$FAILED" -gt 0 ]; then
  exit 1
fi
PUBEOF

chmod +x "$REPO_DIR/publish-all.sh"
echo "OK: publish-all.sh"

# --- Generate README.md ---

echo ""
echo "Generating README.md..."

cat > "$REPO_DIR/README.md" << 'READMEEOF'
# ClawHub Skill Repo — clawhub-lint Distribution

This repository packages all 39 [clawhub-lint](https://github.com/suhteevah/clawhub-lint) static analyzers as individually publishable ClawHub skills.

## What's Inside

39 regex-based static analysis tools, each packaged as a standalone ClawHub skill with:

- `SKILL.md` — Frontmatter (name, description, version, tags) + full documentation
- `scripts/patterns.sh` — Pattern definitions (POSIX ERE grep patterns)
- `scripts/scan.sh` — Minimal wrapper that sources patterns and runs the scan
- `scripts/<name>.sh` or `scripts/dispatcher.sh` — Full CLI entry point
- `scripts/analyzer.sh` — Core analysis engine
- `scripts/license.sh` — License validation (free/pro/team tiers)
- `config/` — Hook configurations (lefthook, etc.)
- `templates/` — Report templates

## Analyzers

| # | Skill | Category |
|---|-------|----------|
| 1 | **accesslint** | Web accessibility & WCAG compliance |
| 2 | **apishield** | API security & best practices |
| 3 | **asyncguard** | Async/await anti-patterns |
| 4 | **authaudit** | Authentication & authorization |
| 5 | **bundlephobia** | Bundle size & dependency bloat |
| 6 | **cachelint** | Caching strategy & invalidation |
| 7 | **cloudguard** | Cloud infrastructure security |
| 8 | **concurrencyguard** | Concurrency & race conditions |
| 9 | **configsafe** | Configuration security |
| 10 | **containerlint** | Docker & container best practices |
| 11 | **cronlint** | Cron job & scheduler patterns |
| 12 | **cryptolint** | Cryptography misuse detection |
| 13 | **dateguard** | Date/time handling anti-patterns |
| 14 | **deadcode** | Dead code & unused exports |
| 15 | **doccoverage** | Documentation coverage gaps |
| 16 | **envguard** | Environment variable safety |
| 17 | **errorlens** | Error handling anti-patterns |
| 18 | **eventlint** | Event system & pub/sub patterns |
| 19 | **featurelint** | Feature flag hygiene |
| 20 | **gqllint** | GraphQL schema & query patterns |
| 21 | **httplint** | HTTP client/server best practices |
| 22 | **i18ncheck** | Internationalization & localization |
| 23 | **inputshield** | Input validation & sanitization |
| 24 | **licenseguard** | License compliance & attribution |
| 25 | **logsentry** | Logging quality & sensitive data |
| 26 | **memguard** | Memory management & leaks |
| 27 | **migratesafe** | Database migration safety |
| 28 | **perfguard** | Performance anti-patterns |
| 29 | **pipelinelint** | CI/CD pipeline security |
| 30 | **ratelint** | Rate limiting & throttling |
| 31 | **regexguard** | Regex complexity & ReDoS |
| 32 | **retrylint** | Retry logic & backoff patterns |
| 33 | **schemalint** | Schema validation patterns |
| 34 | **secretscan** | Secret & credential detection |
| 35 | **serdelint** | Serialization/deserialization safety |
| 36 | **sqlguard** | SQL injection & query safety |
| 37 | **styleguard** | CSS/style anti-patterns |
| 38 | **testgap** | Test coverage gaps & anti-patterns |
| 39 | **typedrift** | Type safety & drift detection |

## Quick Start

Scan a project with any single analyzer:

```bash
bash <skill-dir>/scripts/scan.sh /path/to/project
```

## Publishing All Skills

```bash
bash publish-all.sh            # publish all 39 to ClawHub
bash publish-all.sh --dry-run  # preview what would be published
```

## Origin

All patterns originate from [clawhub-lint](https://github.com/suhteevah/clawhub-lint) (3,348+ patterns across 39 analyzers). This repo is the ClawHub distribution channel — each analyzer becomes a standalone, installable skill.

## License

MIT
READMEEOF

echo "OK: README.md"
echo ""
echo "Done. Generated scan.sh for ${#TOOLS[@]} analyzers, publish-all.sh, and README.md."
